// Generated by gencpp from file cranberry_topic/CommLightResponse.msg
// DO NOT EDIT!


#ifndef CRANBERRY_TOPIC_MESSAGE_COMMLIGHTRESPONSE_H
#define CRANBERRY_TOPIC_MESSAGE_COMMLIGHTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cranberry_topic
{
template <class ContainerAllocator>
struct CommLightResponse_
{
  typedef CommLightResponse_<ContainerAllocator> Type;

  CommLightResponse_()
    : result(0)  {
    }
  CommLightResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::cranberry_topic::CommLightResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cranberry_topic::CommLightResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CommLightResponse_

typedef ::cranberry_topic::CommLightResponse_<std::allocator<void> > CommLightResponse;

typedef boost::shared_ptr< ::cranberry_topic::CommLightResponse > CommLightResponsePtr;
typedef boost::shared_ptr< ::cranberry_topic::CommLightResponse const> CommLightResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cranberry_topic::CommLightResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cranberry_topic::CommLightResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cranberry_topic::CommLightResponse_<ContainerAllocator1> & lhs, const ::cranberry_topic::CommLightResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cranberry_topic::CommLightResponse_<ContainerAllocator1> & lhs, const ::cranberry_topic::CommLightResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cranberry_topic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cranberry_topic::CommLightResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cranberry_topic::CommLightResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cranberry_topic::CommLightResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cranberry_topic::CommLightResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cranberry_topic::CommLightResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cranberry_topic::CommLightResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cranberry_topic::CommLightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::cranberry_topic::CommLightResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::cranberry_topic::CommLightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cranberry_topic/CommLightResponse";
  }

  static const char* value(const ::cranberry_topic::CommLightResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cranberry_topic::CommLightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"\n"
;
  }

  static const char* value(const ::cranberry_topic::CommLightResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cranberry_topic::CommLightResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommLightResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cranberry_topic::CommLightResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cranberry_topic::CommLightResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRANBERRY_TOPIC_MESSAGE_COMMLIGHTRESPONSE_H
